# Generated by Django 5.0.4 on 2024-04-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calories',
            new_name='Categories',
        ),
    ]
