# Generated by Django 4.2.11 on 2024-04-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0003_remove_categories_recipes_recipecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/recipes_photos/'),
        ),
    ]
