# Generated by Django 4.2.11 on 2024-04-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0006_recipe_category_delete_recipecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.AddField(
            model_name='categories',
            name='recipe',
            field=models.ManyToManyField(to='recipes_app.recipe'),
        ),
    ]
