# Generated by Django 4.2.11 on 2024-04-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0007_remove_recipe_category_categories_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='recipe',
            field=models.ManyToManyField(default=None, to='recipes_app.recipe'),
        ),
    ]
