# Generated by Django 4.2.11 on 2024-04-19 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_app', '0009_remove_categories_recipe_recipe_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
    ]
